guide/boards/urls.py
from django.urls import path

from . import views

app_name = 'boards'
urlpatterns = [
    path('', views.home, name='home'),
    path('<pk>/', views.board_topics, name='board_topics'),
    path('<pk>/new/', views.new_topic, name='new_topic'),
    path('<pk>/topics/<topic_pk>/', views.topic_posts, name='topic_posts'),
    path('<pk>)/topics/<topic_pk>/reply/', views.reply_topic, name='reply_topic'),
    path('<pk>/topics/<topic_pk>/posts/<post_pk>/edit/',
        views.PostUpdateView.as_view(), name='edit_post'),

]

guide/delivery/urls.py
from django.urls import path
from . import views

app_name = 'delivery'
urlpatterns = [
    path('new_userdetail/', views.new_userdetail, name='new_userdetail'),
    path('display_userdetail/', views.UserDetailDisplay.as_view(), name='display_userdetail'),
    path('edit_userdetail/', views.UserDetailUpdateView.as_view(), name='edit_userdetail'),
    path('new_securityinfo/', views.new_securityinfo, name='new_securityinfo'),
    path('display_securityinfo/', views.UserSecurityInfoDisplay.as_view(), name='display_securityinfo'),
    path('edit_securityinfo/', views.UserSecurityInfoUpdateView.as_view(), name='edit_securityinfo'),
    path('new_useraddress/', views.UserAddressCreateView.as_view(), name='new_useraddress'),
    path('display_useraddress/', views.UserAddressDisplay.as_view(), name='display_useraddress'),
    path('<address_pk>/edit_useraddress/', views.UserAddressUpdateView.as_view(), name='edit_useraddress'),
    path('<address_pk>/delete_useraddress/', views.UserAddressDeleteView.as_view(), name='delete_useraddress'),
]

guide/dpickup/urls.py
from django.urls import path
from . import views

app_name = 'dpickup'
urlpatterns = [
    path('packages_nearby/', views.UserSearchCreateView.as_view(), name='packages_nearby'),
    #path('packages_nearby/', views.packages_nearby, name='packages_nearby'),
    #path('packages_search/', views.packages_search, name='packages_search'),
    #path('<package_pk>/display_userpackage/', views.UserPackageDisplay.as_view(), name='display_userpackage'),
    #path('<address_pk>/edit_useraddress/', views.UserAddressUpdateView.as_view(), name='edit_useraddress'),
    #path('<address_pk>/delete_useraddress/', views.UserAddressDeleteView.as_view(), name='delete_useraddress'),
]

guide/dtest/urls.py
from django.urls import path
from . import views

app_name = 'dtest'
urlpatterns = [
    path('new_testpackage/', views.TestPackageCreateView.as_view(), name='new_testpackage'),
    path('new_package/', views.PackageCreateView.as_view(), name='new_package'),
    #path('<package_pk>/display_userpackage/', views.UserPackageDisplay.as_view(), name='display_userpackage'),
    #path('<address_pk>/edit_useraddress/', views.UserAddressUpdateView.as_view(), name='edit_useraddress'),
    #path('<address_pk>/delete_useraddress/', views.UserAddressDeleteView.as_view(), name='delete_useraddress'),
]

guide/guide/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
    path('ajaxtest/', include('ajaxtest.urls')),
    path('accounts/', include('accounts.urls')),
    path('delivery/', include('delivery.urls')),
    path('dmanage/', include('dmanage.urls')),
    path('dpickup/', include('dpickup.urls')),
    path('dtest/', include('dtest.urls')),
    #path('payments/', include('payments.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

guide/dpickup/models.py
from django.db import models
from django.contrib.auth.models import User

class UserSearch(models.Model):

    customer = models.ForeignKey(User, related_name='usersearch', on_delete=models.DO_NOTHING)
    date_searched = models.DateTimeField(auto_now_add=True) #Adds current Date and Time
    search_adrs = models.CharField(max_length = 255)
    search_adrs_lat = models.DecimalField(max_digits=10, decimal_places=6, default = 0.0)
    search_adrs_lng = models.DecimalField(max_digits=10, decimal_places=6, default = 0.0)

    def __str__(self):
        return self.customer.username

guide/dpickup/forms.py
from django import forms
from dpickup.models import UserSearch

class UserSearchForm(forms.ModelForm):
    class Meta:
        model = UserSearch
        fields = (
            "search_adrs",
            "search_adrs_lat",
            "search_adrs_lng")
        widgets={
            "search_adrs":forms.TextInput(attrs={'placeholder':'Choose Region'}),
            "search_adrs_lat":forms.NumberInput(attrs={'type':'hidden', 'min' : '0'}),
            "search_adrs_lng":forms.NumberInput(attrs={'type':'hidden', 'min' : '0'}),
            }

guide/dpickup/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import UpdateView, DetailView, FormView, ListView, CreateView
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from math import radians, cos, sin, asin, sqrt

from django.template.loader import render_to_string
from django.http import JsonResponse
from django.conf import settings

from dmanage.models import UserPackage
from delivery.models import UserAddress
from dpickup.forms import UserSearchForm

# Create your views here.
@method_decorator(login_required, name='dispatch')
class UserSearchCreateView(CreateView):
    template_name = "dpickup/packagenearby.html"
    form_class = UserSearchForm
    success_url = reverse_lazy("boards:home")
    data = dict()
    #context_object_name = 'distances'

    def form_valid(self, form):
        detail = form.save(commit=False)
        detail.customer = self.request.user
        search_adrs_lat = form.cleaned_data['search_adrs_lat']
        search_adrs_lng = form.cleaned_data['search_adrs_lng']
        detail.save()

        self.data['form_is_valid'] = True
        distances = UserPackage.objects.with_distance(search_adrs_lat, search_adrs_lng)
        self.data['html_packages_list'] = render_to_string('dpickup/includes/partial_packages_list.html', {
                'distances': distances
            })

        if detail is not None:
            return JsonResponse(self.data)
        else:
            return super(UserSearchCreateView, self).form_valid(form)

    def get_object(self, queryset=None):
        return self.request.user.usersearch

    def get_context_data(self, **kwargs):
        context = super(UserSearchCreateView, self).get_context_data(**kwargs)
        point = UserAddress()
        lattitude = point.get_permanent_lat()
        longitude = point.get_permanent_lng()
        context['distances'] = UserPackage.objects.with_distance(lattitude, longitude)
        context['GMAPS'] = settings.GOOGLE_API_KEY
        return context

""" def packages_nearby(request):
    point = UserAddress()
    form = UserSearchForm()
    lattitude = point.get_permanent_lat()
    longitude = point.get_permanent_lng()
    distances = UserPackage.objects.with_distance(lattitude, longitude)
    return render(request, 'dpickup/packagenearby.html', {'distances': distances, 'form': form})

@login_required
def packages_search(request):

    data = dict()

    if request.method == 'POST':
        form = UserSearchForm(request.POST)
        if form.is_valid():
            detail = form.save(commit=False)
            detail.customer = request.user
            search_adrs_lat = form.cleaned_data['search_adrs_lat']
            search_adrs_lng = form.cleaned_data['search_adrs_lng']
            detail.save()

            data['form_is_valid'] = True
            distances = UserPackage.objects.with_distance(search_adrs_lat, search_adrs_lng)
            data['html_packages_list'] = render_to_string('dpickup/includes/partial_packages_list.html', {
                'distances': distances
            })

        else:
            data['form_is_valid'] = False
    else:
        form = UserSearchForm()

    context = {'form': form, 'GMAPS' : settings.GOOGLE_API_KEY}
    data['html_form'] = render_to_string('dpickup/includes/partial_packages_search.html',
        context,
        request=request,
    )
    return JsonResponse(data) """

guide/dpickup/templates/dpickup/delete_useraddress.html
{% extends 'base.html' %}
{% load form_tags widget_tweaks %}

{% block title %}Delete Address{% endblock %}

{% block stylesheet %}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
  <li class="breadcrumb-item active">Delete Address</li>
{% endblock %}

{% block content %}
  <form method="post" novalidate>
      {% csrf_token %}
    <p>Are you sure you want to delete "{{ address.point_of_contact }}"?</p>
<button type="submit" class="btn btn-success">Confirm Delete</button>
<a href="{% url 'delivery:display_useraddress' %}" class="btn btn-outline-secondary" role="button">Cancel</a>
</form>

{% endblock %}

guide/dpickup/templates/dpickup/display_userpackage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Package Information{% endblock %}
{% block stylesheet %}
 
{% endblock %}
{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
  <li class="breadcrumb-item active">Package Information</li>
{% endblock %}


{% block content %}
{% if user.is_authenticated %}

<table class="table table-bordered">
    <thead class="thead-inverse">
    </thead>
    <tbody>
  
        <tr>
            <td>pickup_adrs</td>
            <td>{{ package.pickup_adrs }}</td>
          </tr>
  
          <tr>
              <td>delivery_adrs</td>
              <td>{{ package.delivery_adrs }}</td>
            </tr>
            <tr>
                <td>delivery_timeline</td>
                <td>{{ package.delivery_timeline }}</td>
            </tr>  
            <tr>
                <td>package_type</td>
                <td>{{ package.package_type }}</td>
              </tr>

              <tr>
                  <td>package_Description</td>
                  <td>{{ package.package_description }}</td>
                </tr>
              <tr>
                      <td>package_Dimensions</td>
                      <td>{{ package.package_dimensions }}</td>
                    </tr>

              <tr>
                        <td>package_weight</td>
                        <td>{{ package.package_weight }} lb</td>
                      </tr>

              <tr>
                          <td>package_value</td>
                          <td>USD {{ package.package_value }}</td>
                        </tr>
  
    </tbody>
  </table>
 
  {% if not package.payment_status %}
  <a href="" class="btn btn-primary" role="button">Edit</a>&nbsp;
  <a href="" class="btn btn-primary" role="button">Continue and Pay USD {{ package.shipping_charge }}</a>
  {% endif %}  

{% endif %}

{% endblock %}

guide/dpickup/templates/dpickup/edit_useraddress.html
{% extends 'base.html' %}
{% load form_tags widget_tweaks %}

{% block title %}Edit Address{% endblock %}

{% block stylesheet %}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
  <li class="breadcrumb-item active">Edit Address</li>
{% endblock %}

{% block content %}
<div id="locationField" class="form-group">
    <input id="autocomplete" placeholder="Start typing your address"
           onFocus="geolocate()" type="text" size="35" class="form-control"></input>
  </div>

  <form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/columnForm.html' %}
<button type="submit" class="btn btn-success">Save Changes</button>
<a href="{% url 'delivery:display_useraddress' %}" class="btn btn-outline-secondary" role="button">Cancel</a>
</form>

    
    <script>
        // This example displays an address form, using the autocomplete feature
        // of the Google Places API to help users fill in the information.
  
        // This example requires the Places library. Include the libraries=places
        // parameter when you first load the API. For example:
        // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">
  
        var placeSearch, autocomplete;
        var componentForm = {
          street_number: 'short_name',
          route: 'long_name',
          locality: 'long_name',
          administrative_area_level_1: 'short_name',
          country: 'long_name',
          postal_code: 'short_name'
        };
        
//        <!-- var place = autocomplete.getPlace(); -->
  
//  <!-- var lat = place.geometry.location.lat(), -->
//      <!-- lng = place.geometry.location.lng(); -->
  
//  <!-- // Then do whatever you want with them -->
  
//  <!-- console.log(lat); -->
//  <!-- console.log(lng); -->
  
//  <!-- console.warn('Warning: I didn\'t test this code!'); -->
  
        function initAutocomplete() {
          // Create the autocomplete object, restricting the search to geographical
          // location types.
          autocomplete = new google.maps.places.Autocomplete(
              /** @type {!HTMLInputElement} */(document.getElementById('autocomplete')),
              {types: ['geocode']});
  
          // When the user selects an address from the dropdown, populate the address
          // fields in the form.
          autocomplete.addListener('place_changed', fillInAddress);
        }
  
        function fillInAddress() {
          // Get the place details from the autocomplete object.
          var place = autocomplete.getPlace();
  
          for (var component in componentForm) {
            document.getElementById(component).value = '';
            document.getElementById(component).disabled = false;
          }

          // Get each component of the address from the place details
          // and fill the corresponding field on the form.
          for (var i = 0; i < place.address_components.length; i++) {
            var addressType = place.address_components[i].types[0];
            if (componentForm[addressType]) {
              var val = place.address_components[i][componentForm[addressType]];
              document.getElementById(addressType).value = val;
              //document.getElementById(addressType).disabled = true;
            }
          }
        }
  
        // Bias the autocomplete object to the user's geographical location,
        // as supplied by the browser's 'navigator.geolocation' object.
        function geolocate() {
          if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
              var geolocation = {
                lat: position.coords.latitude,
                lng: position.coords.longitude
              };
              var circle = new google.maps.Circle({
                center: geolocation,
                radius: position.coords.accuracy
              });
              autocomplete.setBounds(circle.getBounds());
            });
          }
        }
      </script>
      <script src="https://maps.googleapis.com/maps/api/js?key={{GMAPS}}&libraries=places&callback=initAutocomplete"
          async defer></script>
{% endblock %}

guide/dpickup/templates/dpickup/packagenearby.html
{% extends 'base.html' %}
{% load form_tags widget_tweaks %}
{% load static %}
{% block title %}Packages in your area{% endblock %}

{% block stylesheet %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<style>
  .pac-container {
      z-index: 10000 !important;
  }
</style>
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
  <li class="breadcrumb-item active">Packages Nearby</li>

{% endblock %}

{% block content %}

  <!-- BUTTON TO TRIGGER THE ACTION 
  <p>
    <button type="button" class="btn btn-primary js-search-package">
      <span class="glyphicon glyphicon-plus"></span>
      Nearby Search
    </button>
  </p>-->
  <div id="modal-package1">
  {% include 'dpickup/includes/partial_packages_search.html' %}
  </div>
<table class="table" id="package-table">
  <thead class="thead-inverse">
    <tr>
      <th>Package Type</th>
      <th>Pickup Distance</th>
      <th>Weight</th>
      <th>Dimensions</th>
      <th>Pickup</th>
      <th>Delivery</th>
      <th>Offer</th>
      <th>Timeline</th>
      <th>Distance</th>
    </tr>
  </thead>
  <tbody>
    {% include 'dpickup/includes/partial_packages_list.html' %}
  </tbody>
</table>

{% endblock %}

{% block javascript %}
  <script src="{% static 'dpickup/js/packagenearby.js' %}"></script>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key={{GMAPS}}&libraries=places"
          async defer></script>
{% endblock %}